### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by jordivila** [rxaviers/cldr-data-downloader#16]
When I "npm_install" for the first time cldr-data-downloader crashes. After this first time everything works fine. 

Same beahviour when I deploy to azure. When new version is updated and deployment script try to "npm_install" for the first time it crashes. Subsequent deployments work fine.

This time the error was "Cannot find module 'tough-cookie' but the module name changes on every attempt.

Any idea would be helpfull.

Thank you anyway
---------------------------------------------------------------------

module.js:340
    throw err;
          ^
Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\myusername\Documents\GitHub\myprojectname\node_modules\cldr-data-downloader\node_modules\request\lib\cookies.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN engine hawk@3.1.2: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.29","npm":"1.4.14"})
npm ERR! cldr-data@28.0.3 install: `node install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the cldr-data@28.0.3 install script.
npm ERR! This is most likely a problem with the cldr-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cldr-data
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\jv.io\Documents\GitHub\userAdmin
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
-

**Comment by rxaviers** [comment]
Hi @jordivila, thanks for filing this issue and sorry for my delay responding to it.

I am unable to reproduce due to different OS. Sorry. But, I'm open for a PR fixing it. Thanks
