### ISSUE TITLE
npm install cldr-data fails at node install.js

### ISSUE THREAD

**Issue by clazette** [rxaviers/cldr-data-downloader#19]
**The issue began with this post** - [Initial Issue](https://github.com/jquery/globalize/issues/633)

**Below is the original error received when attempting npm install globalize cldr-data:**

D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\bin>node < my-downloader.js
GET http://www.unicode.org/Public/cldr/26/json.zip
D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\lib\download.js:51
throw error;
^

Error: connect ECONNREFUSED 216.97.88.9:80
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect as oncomplete

D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\bin>node < my-downloader.js
GET https://github.com/unicode-cldr/cldr-core/archive/29.0.0.zip
D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\lib\download.js:51
throw error;
^

Error: connect ECONNREFUSED 192.30.253.113:443
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect as oncomplete

**Additional t-shooting has resulted in identifying that the cldr-data install is the issue.**

**I attempted the following with cldr-data-downloader.**

**I tried the file that's listed in the usage example as well as one of the CDLR 29 links to no avail.**

D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\bin>node < my-downloader.js
GET http://www.unicode.org/Public/cldr/26/json.zip
D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\lib\download.js:51
throw error;
^

Error: connect ECONNREFUSED 216.97.88.9:80
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect as oncomplete

D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\bin>node < my-downloader.js
GET https://github.com/unicode-cldr/cldr-core/archive/29.0.0.zip
D:\Demo\Globalization\packages\node_modules\cldr-data-downloader\lib\download.js:51
throw error;
^

Error: connect ECONNREFUSED 192.30.253.113:443
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect as oncomplete

**Comment by rxaviers** [comment]
Thanks for filing the issue here. Please let me know if you find additional details about the proxy tests. Thanks

**Comment by clazette** [comment]
No problem. I don't even know what I am going to try next relative to identifying the cause. As of now, I am trying to work around the issue by manually retrieving the necessary files.

**Comment by rxaviers** [comment]
The first step is try to figure out more details about the failure. In order to do that, use downloader (more info in the README) to fetch CLDR from https://github.com/unicode-cldr/cldr-core/archive/29.0.0.zip, which is expected to fail in your environment. In such case, you can edit your local copy of https://github.com/rxaviers/cldr-data-downloader/blob/master/lib/download.js#L44 and try to output additional error information.

**Comment by clazette** [comment]
The resolution ended up being proxy related and involved setting the following configuration values.

**npm config:**
npm set proxy _yourproxyurlandport_
npm set https-proxy _yourproxyurlandport_

**Windows Environment Variable:**
Run cmd as administrator
set HTTP_PROXY=_yourproxyurlandport_

**Comment by rxaviers** [comment]
Awesome! I'm glad you figured it out, good job. That piece of information would fit well in the README of this project. Would you like to submit a PR? Thanks

**Comment by clazette** [comment]
Will do.
