### ISSUE TITLE
Error requesting archive

### ISSUE THREAD

**Issue by KevinBusse** [rxaviers/cldr-data-downloader#27]
Running `npm i cldr-data` fails:

I tried pinning it to anything between 29.0.0 and 31.0.2 and all versions fail with one or the other download resulting in an 500 error.

### Output

```
> cldr-data@31.0.2 install ...\node_modules\cldr-data
> node install.js

GET `https://github.com/unicode-cldr/cldr-core/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-dates-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-misc-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/31.0.1.zip`
GET `https://github.com/unicode-cldr/cldr-units-modern/archive/31.0.1.zip`
  [----------------------------------------] 9236020/Infinity 0% 0.0s...\node_modules\cldr-data-downloader\lib\download.js:134
      throw error;
      ^

Error: Error requesting archive.
Status: 500
Request options: {
  "url": "https://github.com/unicode-cldr/cldr-localenames-modern/archive/31.0.1.zip",
  "headers": {
    "User-Agent": "curl/7.21.4 (universal-apple-darwin11.0) libcurl/7.21.4 OpenSSL/0.9.8r zlib/1.2.5"
  },
  "followRedirect": true,
  "encoding": null
}
Response headers: {
  "content-length": "27",
  "access-control-allow-origin": "https://render.githubusercontent.com",
  "content-security-policy": "default-src 'none'; style-src 'unsafe-inline'",
  "strict-transport-security": "max-age=31536000",
  "vary": "Authorization,Accept-Encoding",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-xss-protection": "1; mode=block",
  "date": "Wed, 23 Aug 2017 13:06:34 GMT",
  "x-github-request-id": "F881:2B768:DBDE:13592:599D7DD3",
  "connection": "close"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/rxaviers/cldr-data-downloader
    at Request._callback (...\node_modules\cldr-data-downloader\lib\download.js:126:15)
    at Request.self.callback (...\node_modules\request\request.js:187:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (...\node_modules\request\request.js:1044:10)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (...\node_modules\request\request.js:965:12)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
```

**Comment by savelievser** [comment]
I have the same problem!

**Comment by BingoRUS** [comment]
The same here...

**Comment by savelievser** [comment]
Problem is not reproduced anymore. Seems like GitHub had some problems on servers.

**Comment by rxaviers** [comment]
Thanks for reporting and for checking it's working again. Closing...
