### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by blemaire** [rxaviers/cldr-data-downloader#65]
When installing cldr-data I get the following error:

Whops Error making request.
Error: error request aborted
    at createError (C:\Users\...\node_modules\axios\lib\core\createError.js:16:15)
    at IncomingMessage.handlerStreamAborted (C:\Users\...\node_modules\axios\lib\adapters\http.js:301:18)
    at IncomingMessage.emit (events.js:315:20)
    at TLSSocket.socketCloseListener (_http_client.js:426:11)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7)

Thanks alot

**Comment by mazenemam19** [comment]
I keep encountering the same error when I install my node modules. Any idea why this error keeps happening? It's really frustrating.
